import { CELL_WIDTH } from './settings.js';

// Zombie types
export const ZOMBIE_TYPES = {
  BASIC: {
    key: 'basic',
    name: 'Green',
    cost: 50,
    hp: 150,
    speed: 25,         // pixels per second
    damage: 20,
    attackSpeed: 1000, // ms between attacks
    color: 0x5b8a3c,
    description: 'Basic zombie. Slow but steady.',
    projectileSpeed: 0,
    piercing: false,
  },
  FAST: {
    key: 'fast',
    name: 'Runner',
    cost: 50,
    hp: 20,
    speed: 100,
    damage: 15,
    attackSpeed: 600,
    color: 0xc43c3c,
    description: 'Fast zombie. Fragile but quick.',
    projectileSpeed: 0,
    piercing: false,
  },
  TANK: {
    key: 'tank',
    name: 'Shield',
    cost: 100,
    hp: 400,
    speed: 40,
    damage: 5,
    attackSpeed: 1500,
    color: 0x3c5b8a,
    description: 'Tanky zombie. Absorbs punishment.',
    projectileSpeed: 0,
    piercing: false,
  },
  SPITTER: {
    key: 'spitter',
    name: 'Spitter',
    cost: 100,
    hp: 75,
    speed: 20,
    damage: 30,
    attackSpeed: 2000,
    color: 0x8a3c5b,
    description: 'Ranged zombie. Attacks from a distance.',
    projectileSpeed: 300,
    piercing: false,
  },
  JUMPER: {
    key: 'jumper',
    name: 'Jumper',
    cost: 125,
    hp: 50,
    speed: 15,
    damage: 60,
    attackSpeed: 3000,
    color: 0x9b59b6,
    description: 'Leaps to the nearest plant. Bypasses the front line.',
    projectileSpeed: 0,
    piercing: false,
  },
};

// Plant types (enemies)
export const PLANT_TYPES = {
  PEASHOOTER: {
    key: 'peashooter',
    name: 'Peashooter',
    hp: 120,
    damage: 2,
    attackSpeed: 1000, // ms between shots
    range: 9 * CELL_WIDTH,
    color: 0x4caf50,
    projectileSpeed: 900,
    piercing: false,
  },
  SUNFLOWER: {
    key: 'sunflower',
    name: 'Sunflower',
    hp: 30,
    damage: 8,
    attackSpeed: 2000,
    range: 9 * CELL_WIDTH,
    color: 0xffc107,
    piercing: true,
    projectileSpeed: 5000,
  },
  SUPER_SUNFLOWER: {
    key: 'super_sunflower',
    name: 'Super Sunflower',
    hp: 10,
    damage: 500,
    attackSpeed: 20000,
    range: 9 * CELL_WIDTH,
    color: 0xffb07a,
    piercing: true,
    projectileSpeed: 5200,
  },
  WALLNUT: {
    key: 'wallnut',
    name: 'Wall-nut',
    hp: 400,
    damage: 0,
    attackSpeed: 0,
    range: 0,
    color: 0x795548,
    projectileSpeed: 0,
    piercing: false,
  },
  SNOWPEA: {
    key: 'snowpea',
    name: 'Snow Pea',
    hp: 100,
    damage: 10,
    attackSpeed: 2000,
    range: 9 * CELL_WIDTH,
    color: 0x03a9f4,
    slowFactor: 0.2,
    projectileSpeed: 50,
    piercing: false,
  },
};

